### ISSUE TITLE
[Bug] Couldn't find gameobject with guid

### ISSUE THREAD

**Issue by 3ti65** [Powback/MapEditor#335]
Repro:

1. Spawn object
2. Delete that object
3. Mouse over where that object was -> it will print the error in the ingame console:

![image](https://user-images.githubusercontent.com/12377272/156934445-c5b23507-05c6-4bf5-9afe-05dfbaafb576.png)

**Comment by FoolHen** [comment]
Fixed in ca9b14b435d99f1ed146376c39a7300a961a8278

**Comment by 3ti65** [comment]
still happens:

![image](https://user-images.githubusercontent.com/12377272/158726257-8177dd50-9a03-44f1-be98-c4e627e1b9b9.png)
